### ISSUE TITLE
Problem with generated output

### ISSUE THREAD

**Issue by AaronNGray** [fabiospampinato/pacco#2]
I am trying to get the same type of generated output as cash.

My code is here https://github.com/AaronNGray/pacco-typescript-example

I am getting function closure style :-
```
/* MIT https://github.com/AaronNGray/pacco-typescript-example */
var test;
(function (test) {
    class Test {
        constructor(options) {
            console.log("Test.constructor()");
        }
        test() {
            console.log("Test.test()");
        }
    }
    test.Test = Test;
    ;
})(test || (test = {}));
```
Instead of the open format in https://github.com/kenwheeler/cash/blob/master/dist/cash.esm.js

I copied the configuration files from cash and I have only modified "cash" to "test", but it does not seem to be working.

I am at a loss as there seems to be no documentation and I don't have the time to delve deeper into pacco's code.

**Comment by fabiospampinato** [comment]
That's the kind of output that the typescript compiler gives for your code, try running `tsc src/test.ts`.

I'm not sure what this issue is about, if the problem is with the parenthesis I'm afraid that's what the typescript compiler is outputting, why are you wrapping your code in `declare module`?

**Comment by AaronNGray** [comment]
I am following cash and using the same config files as it uses. But am getting different results. If you look at https://github.com/kenwheeler/cash/blob/master/dist/cash.esm.js compared to what I am getting you will see what I mean.

**Comment by fabiospampinato** [comment]
I've looked at both files I don't see what you mean. You're not trying to bundle Cash's source code, so why would you expect the same output?

**Comment by AaronNGray** [comment]
cash's esm.js file is not enclosed in a function closure. I am trying to get the same type of code output. Please build cash look at cash.esm.js, then run my code which uses similar configuration except for cash renamed to test and at its output which I have quoted above.

**Comment by fabiospampinato** [comment]
I told you already that I've read both files. Did you even read my answer above?

> That's the kind of output that the typescript compiler gives for your code, try running tsc src/test.ts.

I don't think this issue has anything to do with pacco itself.

**Comment by AaronNGray** [comment]
What I am trying to understand is how is cash getting that output, without functions closure ?

**Comment by fabiospampinato** [comment]
> if the problem is with the parenthesis I'm afraid that's what the typescript compiler is outputting, why are you wrapping your code in declare module?

_ why are you wrapping your code in declare module?_

**Comment by AaronNGray** [comment]
I don't know I was following what cash does :- https://github.com/kenwheeler/cash/blob/master/pacco.json

**Comment by AaronNGray** [comment]
`declare module` does not make any different AFAICS

**Comment by fabiospampinato** [comment]
> declare module does not make any different AFAICS

Of course it does. But even if if didn't then: why are you writing it?

**Comment by AaronNGray** [comment]
okay I just replace cash'es source code with my single file and it is done somehow in the TypeScript code !

**Comment by AaronNGray** [comment]
> Of course it does. But even if if didn't then: why are you writing it?

I don't know I was following what cash does

And I tried removing it and I the output was the same
